name: iterate a string array

on:
  workflow_dispatch:
    inputs:
      feature_branches:
        description: 'feature branches to be merged separated by commas'
        required: true
      number_of_feature_branches:
        description: 'number of feature branches'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PUSH_TOKEN }}
          
      - name: iterate using for loop
        run: |
          IFS=',' read -r -a array <<< "feature1,feature2"
          for index in "${!array[@]}" 
          do
            echo "${array[index]}"
          done
