name: iterate a string array

on:
  workflow_dispatch:
    inputs:
      feature_branches:
        description: 'feature branches to be merged separated by commas'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.MATRIX }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PUSH_TOKEN }}
          
      - name: iterate using for loop
        id: step1
        run: |
          BRANCHES='${{ github.event.inputs.feature_branches }}'
          echo "MATRIX=${BRANCHES}" >> $GITHUB_OUTPUT 
          
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branches: ${{ needs.job1.outputs.output1 }}
    steps:
    - run: echo "${{ matrix.branches }}"        
