name: using step output as matrix for another job

on:
  workflow_dispatch:
    

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::['feature-1', 'feature-2']"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.job1.outputs.matrix }}
    steps:
    - run: build
